### ISSUE TITLE
Please make this a Composer Package

### ISSUE THREAD

**Issue by thebeline** [vanderlee/PHP-stable-sort-functions#1]
Talk about timing.  This is great.

Do you have any `var_export` examples of the stability of these (just for quick comparisons sake) against the SPL functions?

**Comment by thebeline** [comment]
Also, came here for the `uasort` implementation, so I will ask: While your `suasort` implementation is quite a bit more concise than the PHP.net example (http://php.net/manual/en/function.uasort.php#114535), can you confirm whether or not it's time complexity is less or greater?

**Comment by thebeline** [comment]
Two things, I ran a comparison against `uasort` and the `stable_uasort` on the PHP.net link.  This is stable (surprise).  Awesome - http://ideone.com/TBbLT3

Then I ran some performance benchmarks, sorting a list of 100, 1000 times.  Your Solution was only once again slower than `uasort`, and the PHP.net example was roughly 5 times slower:

```
Starting uasort:
Executing Rerun 1 of 4 for uasort
Rerun 1 of 4 for uasort completed successfully in 2.53 seconds.
Rerun 2 of 4 for uasort completed successfully in 2.63 seconds.
Rerun 3 of 4 for uasort completed successfully in 2.52 seconds.
Rerun 4 of 4 for uasort completed successfully in 2.57 seconds.
Tests for uasort completed successfully in 10.59 seconds.
Starting stable_uasort:
Rerun 1 of 4 for stable_uasort completed successfully in 12.97 seconds.
Rerun 2 of 4 for stable_uasort completed successfully in 12.91 seconds.
Rerun 3 of 4 for stable_uasort completed successfully in 12.45 seconds.
Rerun 4 of 4 for stable_uasort completed successfully in 13.39 seconds.
Tests for stable_uasort completed successfully in 51.89 seconds.
Starting suasort:
Rerun 1 of 4 for suasort completed successfully in 5.51 seconds.
Rerun 2 of 4 for suasort completed successfully in 5.3 seconds.
Rerun 3 of 4 for suasort completed successfully in 5.56 seconds.
Rerun 4 of 4 for suasort completed successfully in 5.24 seconds.
Tests for suasort completed successfully in 21.91 seconds.
```

Cheers!  Now get this on Packagist. ;-)

**Comment by vanderlee** [comment]
I must confess I have not timed any of them. I just wanted a set of stable sorts with performance being no priority. That being said, I'm happy `suasort` seems to run so well :)

The stable_uasort() seems to implement it's own (looks like a very basic quicksort with actual recursion) sorting algorithm, whereas my collection uses PHP builtin functions where it can; particularly for arrays these tend to be "unbeatable". There should still be some room for improvements though.

As for Packagist, I'm afraid I have no experience with that. I'd be glad to submit it there if you could help out.
