### ISSUE TITLE
Release 2.0.3

### ISSUE THREAD

**Issue by janpapenbrock** [vanderlee/PHP-stable-sort-functions#10]
Hey, nice library.

Can you tag a release 2.0.3 please, so that #8 is available when using composer like `"vanderlee/php-stable-sort-functions": "~2.0"`?

Thanks.

**Comment by vanderlee** [comment]
No problem. 2.0.3 is tagged and pushed.

**Comment by janpapenbrock** [comment]
Well that was quick - thanks a lot!
