### ISSUE TITLE
Feature request: Use native functions when on PHP >= 8

### ISSUE THREAD

**Issue by jlherren** [vanderlee/PHP-stable-sort-functions#14]
All sorting functions in PHP 8 are stable, see [RFC](https://wiki.php.net/rfc/stable_sorting). It would be neat if this library would silently use the native functions instead of the custom implementations when running on PHP 8. This would allow to write code that works on PHP 7 and PHP 8, the later with increased performance.

**Comment by vanderlee** [comment]
That makes a lot of sense. I'll see if I can find some time to work on this. Should be a pretty trivial check for `PHP_MAJOR_VERSION >= 8`. Feel free to submit a PR if you want to hasten this fix.

**Comment by vanderlee** [comment]
Just updated the code to revert to native methods if PHP 8+. Released as 2.0.6

**Comment by jlherren** [comment]
Wow, so fast! Thanks a lot!
