### ISSUE TITLE
Depends on undefined behaviour for PHP sort functions regarding internal array pointer

### ISSUE THREAD

**Issue by emilv** [vanderlee/PHP-stable-sort-functions#5]
[This call to key()](https://github.com/vanderlee/PHP-stable-sort-functions/blob/dba539ea79a17ab0a2851da5172263bfb6ab5b4d/functions/sasort.php#L16) assumes that the preceding `asort` call did reset or preserve the internal array pointer, which is [not documented](http://php.net/asort). This can be solved by an explicit call to `reset()` after the sort but before the `key()` call. Depending on the internal array pointer is always sketchy in all but the most basic cases because the PHP manual gives almost no guarantees about when it is or is not changed.

**Comment by vanderlee** [comment]
Thanks for the info. It's fixed and version bumped to 1.0.3.

**Comment by emilv** [comment]
:+1:
