### ISSUE TITLE
Update packagist

### ISSUE THREAD

**Issue by adamk33n3r** [vanderlee/PHP-stable-sort-functions#7]
Packagist doesn't have the new version with the utility classes.

**Comment by vanderlee** [comment]
Apparently, Packagist doesn't have any easy path to change the name of a package.
I think the easiest solution for all is to rename it back to PHP-stable-sort-functions again.
It's not the best descriptive name, but it's not too bad either.

**Comment by vanderlee** [comment]
Renamed it. I think that should fix the mess I made :)

**Comment by adamk33n3r** [comment]
Cool thanks! :)
