### ISSUE TITLE
Issue with non-integer value

### ISSUE THREAD

**Issue by inv-senchuthomas** [vanderlee/PHP-stable-sort-functions#9]
Returning non-integer values from the comparison function, such as float, will result in an internal cast to integer of the callback's return value. So values such as 0.99 and 0.1 will both be cast to an integer value of 0, which will compare such values as equal.

**Comment by vanderlee** [comment]
Casting to integer is consistent with PHP's builtin sort functions such as `usort`, so cannot be changed without introducing incompatible behaviour.
It's the callback's responsibility to return a valid integer value.

**Comment by inv-senchuthomas** [comment]
My use case is to apply stable sort on values like  0. 99, 0. 89...  but when I used usort on this varible it is considerd as equal and giving diffrent sort order.  Will it be posiible to sort this type of values in stable sort order

**Comment by vanderlee** [comment]
Which of the stable sort functions/methods do you want to use? I just added some testcases, and as far as I can tell, they all work will with floating point values.

**Comment by inv-senchuthomas** [comment]
Hai sir,
      I want to usort some json data based on the value of score.  And
normally the score will be floating point values like. 0.99,0.666,0.777
etc.  Will you please help me to stable sort this values based on score.
Any help will be appreciated.

Thank you
